'''
Written by Viraj Jayasinghe
'''

import string
import sys

if __name__=="__main__":
    fid=open('Solar PV 15min Feb 23032020.csv', 'r')
    content=fid.readlines();
    fid.close();

    #initialise the data by putting it into an array
    data=[];
    for i in range(len(content)):
        data.append(content[i].split(','))
        data[-1][2]=data[-1][2].split('\n')[0]

    print(data)

    #pre process the data by getting the total daily energy generated by the pv panels
    ref_date=data[1][0][0:2]
    pv_1_val=float(0);
    pv_2_val=float(0);
    final_vals=[]
    for i in range(1, len(data)):#interate through each 15 minute interval
        if(data[i][0][0:2]==ref_date):#if its the same day, just keep adding it on
            pv_1_val=pv_1_val+float(data[i][1])
            #print(float(data[i][1]))
            pv_2_val = pv_2_val + float(data[i][2])
        else:#if its a different day, save it into the output matrix "final_vals"
            final_vals.append([ref_date, pv_1_val, pv_2_val])
            ref_date=data[i][0][0:2]
            pv_1_val=float(data[i][1])
            pv_2_val=float(data[i][2])
    final_vals.append([ref_date, pv_1_val, pv_2_val])#final date

    #write the final_vals matrix into a csv file in the local drive
    out_str="time,pv_1,pv_2\n"
    for i in range(len(final_vals)-1, -1, -1):
        out_str+="{},{},{}\n".format(final_vals[i][0], final_vals[i][1], final_vals[i][2])
    print(final_vals)

    fid=open('output.csv', 'w')
    fid.write(out_str)
    fid.close()